### ISSUE TITLE
Unable to set up the BoB

### ISSUE THREAD

**Issue by shashvattrip** [mcupak/beacon-of-beacons#47] opened 2015-03-06 20:29 UTC
Order of commands
For Linux:   JBOSS_HOME/bin/standalone.sh -c standalone-full.xml
mvn clean install (inside root of the beacon-of-beacon)
cd bob-rest
mvn wildfly:deploy [Runs successfully]
mvn wildfly:undeploy [Throws the following errors]
Please tell me what's wrong.

Thanks!

------------------------------------------------------------
~/Desktop/apps/ga4g/beacon-of-beacons/bob-rest(branch:master) » mvn test -Parq-wildfly-managed -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building bob-rest 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ bob-rest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ bob-rest ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ bob-rest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ bob-rest ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ bob-rest ---
[INFO] Surefire report directory: /home/shash/Desktop/apps/ga4g/beacon-of-beacons/bob-rest/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.dnastack.bob.rest.IcgcResponseTest
log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.653 sec <<< FAILURE!
Running com.dnastack.bob.rest.CuroverseBeaconizerResponseTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
Running com.dnastack.bob.rest.AmpLabResponseTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
Running com.dnastack.bob.rest.CafeVariomeResponseTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
Running com.dnastack.bob.rest.BobResponseTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
Running com.dnastack.bob.rest.EbiResponseTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
Running com.dnastack.bob.rest.BroadInstituteResponseTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
Running com.dnastack.bob.rest.NcbiResponseTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
Running com.dnastack.bob.rest.KaviarResponseTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
Running com.dnastack.bob.rest.UcscResponseTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
Running com.dnastack.bob.rest.WtsiResponseTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
Running com.dnastack.bob.rest.HelpTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
Running com.dnastack.bob.rest.ItemTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
Running com.dnastack.bob.rest.BeaconsTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
Running com.dnastack.bob.rest.BeaconResponsesTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!

Results :

Tests in error: 
  com.dnastack.bob.rest.IcgcResponseTest: The server is already running! Managed containers do not support connecting to running server instances due to the possible harmful effect of connecting to the wrong server. Please stop server before running or change to another type of container.
  com.dnastack.bob.rest.CuroverseBeaconizerResponseTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
  com.dnastack.bob.rest.AmpLabResponseTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
  com.dnastack.bob.rest.CafeVariomeResponseTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
  com.dnastack.bob.rest.BobResponseTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
  com.dnastack.bob.rest.EbiResponseTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
  com.dnastack.bob.rest.BroadInstituteResponseTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
  com.dnastack.bob.rest.NcbiResponseTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
  com.dnastack.bob.rest.KaviarResponseTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
  com.dnastack.bob.rest.UcscResponseTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
  com.dnastack.bob.rest.WtsiResponseTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
  com.dnastack.bob.rest.HelpTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
  com.dnastack.bob.rest.ItemTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
  com.dnastack.bob.rest.BeaconsTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
  com.dnastack.bob.rest.BeaconResponsesTest: Arquillian has previously been attempted initialized, but failed. See cause for previous exception

Tests run: 15, Failures: 0, Errors: 15, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.440s
[INFO] Finished at: Sat Mar 07 01:54:12 IST 2015
[INFO] Final Memory: 19M/341M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project bob-rest: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/shash/Desktop/apps/ga4g/beacon-of-beacons/bob-rest/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project bob-rest: There are test failures.

Please refer to /home/shash/Desktop/apps/ga4g/beacon-of-beacons/bob-rest/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /home/shash/Desktop/apps/ga4g/beacon-of-beacons/bob-rest/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:87)
	at org.apache.maven.plugin.surefire.SurefirePlugin.writeSummary(SurefirePlugin.java:641)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:615)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:137)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:98)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
-----------

**Comment by mcupak** [comment] 2015-03-09 16:59
The log you attached shows very little data and I wasn't able to reproduce the problem. If you want to run the test suite, make sure the server is not started yet (otherwise you get a port conflict) and $JBOSS_HOME points to the correct location. Also make sure you don't have the war deployed on the server at that point (just in case), i.e. remove it from $JBOSS_HOME/standalone/deployments.

If you just want to use BoB without running the tests, just use the default profile (i.e. don't use "-Parq-wildfly-managed").

Either way, "mvn wildfly:deploy" is the command that deploys BoB to Wildfly. Since that works for you without errors, you should be able to use BoB.

"mvn wildfly:undeploy" is used to remove the app from the server once you're done. You can achieve the same result by removing the war file manually from $JBOSS_HOME/standalone/deployments.

Can you confirm BoB works on your end?

**Comment by shashvattrip** [comment] 2015-03-09 21:26
Hey, I think I have it up and running. But the responses are in XML? Not in JSON? Is there a configuration file that can change it?
Here's a snapshot of the localhost.

![bob-rest](https://cloud.githubusercontent.com/assets/2312691/6564728/0a3cb382-c6d1-11e4-95cc-9a4e7e100333.png)

**Comment by mcupak** [comment] 2015-03-09 21:35
The response format depends on what you set in "Accept" header in your request. JSON is default (try e.g. curl). If you're seeing XML in your browser, it means your browser sets XML as one of the preferred formats in that header.

**Comment by shashvattrip** [comment] 2015-03-10 16:20
Yes, works well with POSTMAN.

**Comment by mcupak** [comment] 2015-03-10 16:35
OK, resolving.

**Closed by mcupak** 2015-03-10 16:35 UTC
